#include<stdio.h>
#include<conio.h>
void main(
)
{
int day;
clrscr();
printf(" the number of the week from 1 to 7:");
scanf("%d",&day);
switch(day)
{
case 1:
printf("the first day of the week is monday");
break;
case 2:
printf("the second day ofthe week is tuesday");
break;
case 3:
printf("the third day ofthe week is wednesday");
break;
case 4:
printf("the fourth day ofthe week is thursday");
break;
case 5:
printf("the fifth day ofthe week is friday");
break;
case 6:
printf("the sixth day ofthe week is saturday");
break;
case 7:
printf("the seventh day ofthe week is sunday");
break;
}
getch();}
